import Head from "next/head"
import Image from "next/image"
import { AudioPlayer } from "../components/AudioPlayer"

export default function Home() {
  return (
    <div className="px-8 bg-clrDark">
      <Head>
        <title>Custom Audio Player</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen py-16 flex-1 flex flex-col justify-center items-center ">
        <AudioPlayer />
      </main>
    </div>
  )
}
